services:
  dock2dockapi:
    depends_on:
      - rabbitmq
    image: dock2dockio/api
    container_name: 'api'
    restart: always
    environment:
      Dock2Dock__ApiKey_FILE: /run/secrets/dock2dock_apikey
      Dock2Dock__BaseUrl: ${DOCK2DOCK_BASEURL}
      
  navbackgroundtasks:
    depends_on:
      - rabbitmq
    image: dock2dockio/nav-tasks
    container_name: 'nav-tasks'
    restart: always
    environment:
      NavApi__Url: ${NAVAPI_URL}
      NavApi__Username: ${NAVAPI_USERNAME}
      NavApi__Password_FILE: /run/secrets/navapi_password
      NavApi__GetSalesOrdersFilter: ${NAVAPI_GET_SALES_ORDERS_FILTER}
      NavApi__SyncSalesOrdersEnabled: ${NAVAPI_SYNC_SALES_ORDERS_ENABLED}
      Jobs__CheckLatestNavSalesOrders__CronExpression: ${NAVAPI_SYNC_SALES_ORDERS_SCHEDULE}
      CronTz: ${CRON_TZ}
    volumes:
      - navbackgroundtasks-config:/app/config
    secrets:
      - navapi_password
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'dock2dock-rabbitmq'
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: Prod

volumes:
  navbackgroundtasks-config:

secrets:
  navapi_password:
    file: ./secrets/navapi_password.txt
  dock2dock_apikey:
    file: ./secrets/dock2dock_apikey.txt
